### ISSUE TITLE
Info "temps de lecture" non pertinent sur les vidéos

### ISSUE THREAD

**Issue by CodeSimcoe** [SCIAM-FR/sciam-fr.github.io#84]
A masquer sur les vidéos ?
![image](https://github.com/user-attachments/assets/86181bfb-fc30-48cc-8209-a4abd15bde12)

**Comment by antoinesd** [comment]
en effet. Je vais regarder comment retirer cette mention

**Comment by CodeSimcoe** [comment]
#86 pour la liste
